### ISSUE TITLE
Add Freebox BitTorrent

### ISSUE THREAD

**Issue by reklatsmasters** [webtorrent/bittorrent-peerid#10]
signatire: `-FX0104-`

peer id:
![image](https://cloud.githubusercontent.com/assets/2255752/13884949/0c2c8c14-ed52-11e5-8ae6-abff2b4d6aa4.png)

ext handshake:
![image](https://cloud.githubusercontent.com/assets/2255752/13884993/39b588d4-ed52-11e5-9ba5-87b40974d4fb.png)

**Comment by devgianlu** [comment]
I've included this in #20
