### ISSUE TITLE
Transfer to WebTorrent organization

### ISSUE THREAD

**Issue by feross** [webtorrent/bittorrent-peerid#12]
Hey @fisch0920, I moved all my personal WebTorrent repos into a new [WebTorrent organization](https://github.com/webtorrent).

If it's okay with you, can you transfer this repo to the "webtorrent" organization? 🙏

**Comment by fisch0920** [comment]
No problem :)

**Comment by feross** [comment]
👍

**Comment by feross** [comment]
This is done now! https://github.com/webtorrent/bittorrent-peerid
