### ISSUE TITLE
Avoid modifying JS built-ins

### ISSUE THREAD

**Issue by feross** [webtorrent/bittorrent-peerid#6]
Is there a good reason to add these functions to `String.prototype` instead of just having them be utility functions?

https://github.com/fisch0920/bittorrent-peerid/blob/master/lib/utils.js#L2

This will change `String` for all other npm modules loaded in the same node program. Maybe it's not a big deal since it will supposedly be in ES6...

**Comment by qgustavor** [comment]
Seems you fixed it in 37b5bb284c31e04ff3008f1659fb241a465f5dc3.

**Comment by feross** [comment]
Yep, thanks. Closed!
