### ISSUE TITLE
Who is BU11A0?

### ISSUE THREAD

**Issue by FLYBYME** [webtorrent/bittorrent-peerid#8]
Im working on getting versions working. Does anyone know what this client is?

name/Version: `BU11A0`

PeerId Hex: `2d4255313141302d66784a72217663513778596b`

**Comment by FLYBYME** [comment]
Also found this client.

name/version: `XF9100`
PeerId Hex: `2d5846393130302d7e5134452e28214b6d363878`

**Comment by FLYBYME** [comment]
Found another

name/version: `tG1400`
PeerId Hex: `2d7447313430302d53442d6662322a5031616153`

**Comment by feross** [comment]
No idea.
